
name: vps-setup

services:
  # https://github.com/GetPageSpeed/MTProxy
  MTProxy:
    container_name: MTProxy
    image: ghcr.io/getpagespeed/mtproxy
    ports:
      - "8443:8443"
    environment:
      - SECRET
      - EXTERNAL_IP
      - DIRECT_MODE=true
      - PORT=8443
      - STATS_PORT=8888
      - WORKERS=1
      - RANDOM_PADDING=true
    volumes:
      - ./vps-setup-data/mtproxy-data:/opt/mtproxy/data:rw
    restart: unless-stopped

  # https://github.com/hwdsl2/docker-ipsec-vpn-server
#  ipsec-vpn:
#    container_name: ipsec-vpn
#    image: hwdsl2/ipsec-vpn-server
#    ports:
#      - "500:500/udp"
#      - "4500:4500/udp"
#    privileged: true
#    environment:
#      - VPN_IPSEC_PSK
#      - VPN_USER
#      - VPN_PASSWORD
#      - VPN_PROTECT_CONFIG
#      - VPN_CLIENT_NAME
#    volumes:
#      - ./vps-setup-data/ipsec-vpn/data:/etc/ipsec.d:rw
#      - ./vps-setup-data/ipsec-vpn/modules:/lib/modules:ro

  # https://github.com/kylemanna/docker-openvpn?tab=readme-ov-file
  ovpn:
    container_name: ovpn
    image: kylemanna/openvpn
    ports:
      - "1194:1194/udp"
    cap_add:
      - NET_ADMIN
    volumes:
      - ./vps-setup-data/ovpn:/etc/openvpn:rw
    restart: unless-stopped

  # https://v2.hysteria.network/docs/advanced/Full-Server-Config
  hysteria:
    image: tobyxdd/hysteria
    container_name: hysteria
    network_mode: "host"
    volumes:
      - ./vps-setup-data/hysteria/acme:/acme:rw
      - ./vps-setup-data/hysteria/hysteria.yaml:/etc/hysteria.yaml:rw
    command: ["server", "-c", "/etc/hysteria.yaml"]
    restart: unless-stopped
